version: '3.8'

services:
  backend:
    container_name: sms-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    restart: unless-stopped
    networks:
      - imraffy-network

  frontend:
    container_name: sms-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3005:3005"
    env_file:
      - ./frontend/.env
    restart: unless-stopped
    networks:
      - imraffy-network

  mobile:
    container_name: sms-mobile
    build:
      context: ./sms-mobile-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  
    restart: unless-stopped
    networks:
      - imraffy-network

networks:
  imraffy-network:
    external: true
