version: '3.8'

services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    restart: unless-stopped
    networks:
      - imraffy-network

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3005:3005"
    env_file:
      - ./frontend/.env
    restart: unless-stopped
    networks:
      - imraffy-network

networks:
  imraffy-network:
    external: true
